language: python
cache: pip
sudo: required
os: trusty

# Test environments
matrix:
  include:
   - env: TOXENV=py34
     python: 3.4
   #- env: TOXENV=py35
   #  python: 3.5
   #- env: TOXENV=py36
   #  python: 3.6


# Make Qt available in virtualenv
virtualenv:
  system_site_packages: true

# Package installation
install:
  - sudo apt-get update
  - apt-cache search pyqt5
  - apt-cache search scintilla
  - sudo apt-get -qq install python3-pyqt5 python3-pyqt5.qsci
  - sudo apt-get install -y python3-pyqt5
  - pip install tox codecov

# Run tests
script:
  - tox

# Register code coverage in coveralls
after_success:
  - codecov